105: Add Pagination and PaginationItem components
vanilla-framework/vanilla-framework-react pull request #117
Opened 2018-01-29 12:19 UTC by Caleb-Ellis

# Done
- Added [Pagination](https://docs.vanillaframework.io/en/patterns/pagination) component and PaginationItem subcomponent
- Added stories/knobs to Storybook
- Added snapshot tests
- Updated to Vanilla 1.6.5 (which fixed single direction pagination)

# QA
- Pull code
- Run `yarn lint` and `yarn test` to ensure there are no linting or testing errors
- Run `./run serve --watch` and navigate to http://localhost:8102/
- Verify the Pagination component in Storybook matches the [Vanilla docs](https://docs.vanillaframework.io/en/patterns/pagination)

# Fixes
Fixes #105

2018-01-29 12:22 UTC, webteam-app commented
Starting demo at: http://vanilla-framework-react-pr-117.run.demo.haus/

2018-01-29 14:22 UTC, anthonydillon requested changes
Suggestion in code

2018-01-29 14:22 UTC, anthonydillon commented on src/lib/components/Pagination/Pagination.js
> +  </footer>
Not sure we should use `footer` we can't be sure this is only footer on the page or in an `section`.

2018-01-29 17:31 UTC, tbille requested changes

2018-01-29 17:31 UTC, tbille commented on src/lib/components/Pagination/PaginationItem.js
> +    className = 'p-pagination__link--next';
`className = className + '--next';`

2018-01-29 17:31 UTC, tbille commented on src/lib/components/Pagination/PaginationItem.js
> +    className = 'p-pagination__link--previous';
className = className + '--previous';

2018-01-30 09:24 UTC, anthonydillon approved these changes
LGTM :+1:

2018-01-30 09:47 UTC, merged