Add Code Numbered component
vanilla-framework/vanilla-framework-react pull request #41
Opened 2017-11-09 16:59 UTC by Caleb-Ellis

# Done
- Added Code Numbered component
- Added story to Storybook
- Added snapshot testing

# QA
- Pull code
- Run `yarn run build` and `yarn run serve`
- Verify the Code Numbered pattern in Storybook
- Verify the Code Numbered test passes and the snapshot is correct

# Fixes
Fixes #36, fixes #37, fixes #38

2017-11-09 17:23 UTC, tbille commented on src/lib/components/CodeNumbered/CodeNumbered.test.js
> +    const codenumbered = ReactTestRenderer.create(<CodeNumbered lines={[
`camelCase` var names

2017-11-09 17:31 UTC, barrymcgee reviewed
I'm not sure passing the code snippet as an array of lines as a named prop is the best approach given this could be used to display some very large code blocks. 

An alternative approach would be to add each line as children of the component, wrapped in `<code>` snippets and iterate over the `this.props.children` object instead?

2017-11-09 17:41 UTC, Lukewh approved these changes
👍 love it. Thanks @Caleb-Ellis

2017-11-09 17:43 UTC, Lukewh commented
@Caleb-Ellis @barrymcgee's point is valid, though I'd maybe go a step further and accept unformatted text and split on new lines and create the array from that?

2017-11-10 09:01 UTC, Caleb-Ellis commented
@barrymcgee good point, didn't really consider how large the code blocks might get. I'll give @Lukewh's idea a go

2017-11-10 11:20 UTC, Lukewh requested changes
Looks good but could we add a test for a 1 liner?

2017-11-10 11:33 UTC, tbille commented
* Not sure if it is really relevant but what happens if I use `tabs` instead of `spaces` for indentation?
If this is relevant it would need a test.
* And what happens if it don't pass code in the component? Is it displayed with no lines? -> I think you need a test for this use case.

2017-11-10 11:53 UTC, Lukewh commented
Also what happens if someone does pass in some markup - we should escape it.

2017-11-13 10:22 UTC, Caleb-Ellis commented
I've changed the component a bit by making it a more generic Code Block with an optional modifier of 'numbered'. Thoughts?
@Lukewh You should be able to pass markup as children now, which will be converted to a string and prettified automatically.
@tbille If nothing is passed through an code block with no lines will show. There are now tests for this as well as single line + multiline codeblocks, with/without the numbered modifier

2017-11-13 10:27 UTC, tbille commented
@Caleb-Ellis `If nothing is passed through, a code block with no lines will show. ` Is it the behavior you want? Wouldn't it be better to have one empty line?

Add lines between tests to make your file more readable :smiley:

2017-11-13 10:32 UTC, Caleb-Ellis commented
@tbille Oops, that's a typo - one empty line will show

2017-11-13 13:12 UTC, Lukewh approved these changes
Looks good thanks @Caleb-Ellis 👍

2017-11-13 13:17 UTC, merged