81: Add Notification component
vanilla-framework/vanilla-framework-react pull request #96
Opened 2018-01-03 10:02 UTC by Caleb-Ellis

# Done
- Added [Notification](https://docs.vanillaframework.io/en/patterns/notification)
- Includes Default, Information, Positive, Caution and Negative types
- Added stories/knobs to Storybook
- Added snapshot tests
- Updated Storybook name in upper-left corner to 'Vanilla Framework React' to be a bit clearer

# QA
- Pull code
- Run `yarn lint` and `yarn test` to ensure there are no linting or testing errors
- Run `./run serve --watch` and navigate to http://localhost:8102/
- Verify the Notification component in Storybook matches the [Vanilla docs](https://docs.vanillaframework.io/en/patterns/notification)

# Fixes
Fixes #81

2018-01-03 10:04 UTC, webteam-app commented
Starting demo at: http://vanilla-framework-react-pr-96.run.demo.haus/

2018-01-03 20:12 UTC, anthonydillon requested changes
Few comments in the code.

2018-01-03 20:12 UTC, anthonydillon commented on src/lib/components/Notification/Notification.js
> +    else if (this.props.information) classString = 'p-notification--information';
This would be a good place to use a switch case.

2018-01-03 20:12 UTC, anthonydillon commented on src/lib/components/Notification/Notification.js
> +  children: PropTypes.node,
Shouldn't a message be required?

2018-01-04 10:19 UTC, Caleb-Ellis commented
@anthonydillon I've now made children a requirement and replaced the if statements with a switch case

2018-01-04 17:36 UTC, tbille commented on src/lib/components/Notification/Notification.js
> +    switch (true) {
don't do this please.
Use `if` or a `list key/value`

2018-01-08 11:42 UTC, webteam-app commented
Starting demo at: http://vanilla-framework-react-pr-96.run.demo.haus/

2018-01-08 11:43 UTC, anthonydillon approved these changes
Thanks :+1:

2018-01-08 12:19 UTC, merged