94: Add Tabs component
vanilla-framework/vanilla-framework-react pull request #97
Opened 2018-01-03 13:43 UTC by Caleb-Ellis

# Done
- Added [Tabs](https://docs.vanillaframework.io/en/patterns/tabs) component and TabsItem subcomponent
- Added stories/knobs to Storybook
- Added snapshot tests

# QA
- Pull code
- Run `yarn lint` and `yarn test` to ensure there are no linting or testing errors
- Run `./run serve --watch` and navigate to http://localhost:8102/
- Verify the Tabs component in Storybook matches the [Vanilla docs](https://docs.vanillaframework.io/en/patterns/tabs)

# Fixes
Fixes #94

2018-01-03 13:45 UTC, webteam-app commented
Starting demo at: http://vanilla-framework-react-pr-97.run.demo.haus/

2018-01-03 20:03 UTC, anthonydillon requested changes
One small comment about the use of tabIndex

2018-01-03 20:03 UTC, anthonydillon commented on src/lib/components/Tabs/TabsItem.js
> +          tabIndex={isSelected ? 0 : -1}
Can you remove this tabIndex as -1 stops a user from tabbing to it.

2018-01-04 10:17 UTC, Caleb-Ellis commented
@anthonydillon I've changed tabIndex to be index + 1 so you can still tab through in order, and added an onKeyPress func so you can navigate the tabs via keyboard

2018-01-08 11:09 UTC, anthonydillon approved these changes
Code looks good

2018-01-08 11:10 UTC, webteam-app commented
Starting demo at: http://vanilla-framework-react-pr-97.run.demo.haus/

2018-01-08 11:40 UTC, merged